// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsbjqcTpxnMshDfUb6Wjzrs3OVM7TbRqk',
    appId: '1:2012933162:web:23a992f09173b082c1a753',
    messagingSenderId: '2012933162',
    projectId: 'finalvimigoapp',
    authDomain: 'finalvimigoapp.firebaseapp.com',
    storageBucket: 'finalvimigoapp.appspot.com',
    measurementId: 'G-NR6MPXYTWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4lkPDydmltPRdGlYVH7iJuClBTiaN--o',
    appId: '1:2012933162:android:02fc3614afae09e6c1a753',
    messagingSenderId: '2012933162',
    projectId: 'finalvimigoapp',
    storageBucket: 'finalvimigoapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrp2VzvlnFuoa7XEgE64zeASE2JBQ6AZ4',
    appId: '1:2012933162:ios:320b0aeb83dcc3a1c1a753',
    messagingSenderId: '2012933162',
    projectId: 'finalvimigoapp',
    storageBucket: 'finalvimigoapp.appspot.com',
    iosBundleId: 'com.example.vimigoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrp2VzvlnFuoa7XEgE64zeASE2JBQ6AZ4',
    appId: '1:2012933162:ios:66f039255d378eb1c1a753',
    messagingSenderId: '2012933162',
    projectId: 'finalvimigoapp',
    storageBucket: 'finalvimigoapp.appspot.com',
    iosBundleId: 'com.example.vimigoapp.RunnerTests',
  );
}
